# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_seal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import consensus_messages_pb2 as consensus__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_seal.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63lient_seal.proto\x1a\x18\x63onsensus_messages.proto\"\x13\n\x11\x43lientSealRequest\"\xa4\x01\n\x12\x43lientSealResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.ClientSealResponse.Status\x12+\n\ncert_votes\x18\x02 \x03(\x0b\x32\x17.SignedConsensusMessage\"5\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x0f\n\x0bNO_RESOURCE\x10\x02\x62\x06proto3')
  ,
  dependencies=[consensus__messages__pb2.DESCRIPTOR,])



_CLIENTSEALRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ClientSealResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_RESOURCE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=180,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_CLIENTSEALRESPONSE_STATUS)


_CLIENTSEALREQUEST = _descriptor.Descriptor(
  name='ClientSealRequest',
  full_name='ClientSealRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=66,
)


_CLIENTSEALRESPONSE = _descriptor.Descriptor(
  name='ClientSealResponse',
  full_name='ClientSealResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ClientSealResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cert_votes', full_name='ClientSealResponse.cert_votes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTSEALRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=233,
)

_CLIENTSEALRESPONSE.fields_by_name['status'].enum_type = _CLIENTSEALRESPONSE_STATUS
_CLIENTSEALRESPONSE.fields_by_name['cert_votes'].message_type = consensus__messages__pb2._SIGNEDCONSENSUSMESSAGE
_CLIENTSEALRESPONSE_STATUS.containing_type = _CLIENTSEALRESPONSE
DESCRIPTOR.message_types_by_name['ClientSealRequest'] = _CLIENTSEALREQUEST
DESCRIPTOR.message_types_by_name['ClientSealResponse'] = _CLIENTSEALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientSealRequest = _reflection.GeneratedProtocolMessageType('ClientSealRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSEALREQUEST,
  __module__ = 'client_seal_pb2'
  # @@protoc_insertion_point(class_scope:ClientSealRequest)
  ))
_sym_db.RegisterMessage(ClientSealRequest)

ClientSealResponse = _reflection.GeneratedProtocolMessageType('ClientSealResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSEALRESPONSE,
  __module__ = 'client_seal_pb2'
  # @@protoc_insertion_point(class_scope:ClientSealResponse)
  ))
_sym_db.RegisterMessage(ClientSealResponse)


# @@protoc_insertion_point(module_scope)
