# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_account.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12node_account.proto\"u\n\tShareInfo\x12\x11\n\tblock_num\x18\x01 \x01(\x04\x12\x14\n\x0c\x66rozen_share\x18\x02 \x01(\x04\x12\x0e\n\x06reward\x18\x03 \x01(\x04\x12\x17\n\x0f\x62lock_timestamp\x18\x04 \x01(\x04\x12\x16\n\x0e\x64\x65\x66rost_months\x18\x05 \x01(\r\"\xce\x02\n\x0bNodeAccount\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x04\x12*\n\nnode_state\x18\x02 \x01(\x0e\x32\x16.NodeAccount.NodeState\x12+\n\nreputation\x18\x03 \x01(\x0b\x32\x17.NodeAccount.Reputation\x12\x16\n\x0c\x66ixed_amount\x18\x04 \x01(\rH\x00\x12\r\n\x03min\x18\x05 \x01(\x08H\x00\x12\r\n\x03max\x18\x06 \x01(\x08H\x00\x12\x1e\n\x16last_defrost_timestamp\x18\x07 \x01(\x04\x12\x1a\n\x06shares\x18\x08 \x03(\x0b\x32\n.ShareInfo\x1a.\n\nReputation\x12\x0e\n\x06\x66rozen\x18\x01 \x01(\x04\x12\x10\n\x08unfrozen\x18\x02 \x01(\x04\",\n\tNodeState\x12\x07\n\x03NEW\x10\x00\x12\n\n\x06OPENED\x10\x01\x12\n\n\x06\x43LOSED\x10\x02\x42\x05\n\x03\x62\x65t\"!\n\tNodeState\x12\x14\n\x0cmaster_nodes\x18\x01 \x03(\t\"\xce\x01\n\x11NodeAccountMethod\"\xb8\x01\n\x06Method\x12$\n TRANSFER_FROM_FROZEN_TO_UNFROZEN\x10\x00\x12)\n%TRANSFER_FROM_UNFROZEN_TO_OPERATIONAL\x10\x01\x12\x19\n\x15INITIALIZE_MASTERNODE\x10\x02\x12\x14\n\x10\x43LOSE_MASTERNODE\x10\x03\x12\x13\n\x0fINITIALIZE_NODE\x10\x04\x12\x0b\n\x07SET_BET\x10\x05\x12\n\n\x06\x44O_BET\x10\x06\"3\n\"NodeAccountInternalTransferPayload\x12\r\n\x05value\x18\x01 \x01(\x04\"L\n\rSetBetPayload\x12\x16\n\x0c\x66ixed_amount\x18\x01 \x01(\x02H\x00\x12\r\n\x03min\x18\x02 \x01(\x08H\x00\x12\r\n\x03max\x18\x03 \x01(\x08H\x00\x42\x05\n\x03\x62\x65tb\x06proto3')
)



_NODEACCOUNT_NODESTATE = _descriptor.EnumDescriptor(
  name='NodeState',
  full_name='NodeAccount.NodeState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPENED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=425,
  serialized_end=469,
)
_sym_db.RegisterEnumDescriptor(_NODEACCOUNT_NODESTATE)

_NODEACCOUNTMETHOD_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='NodeAccountMethod.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSFER_FROM_FROZEN_TO_UNFROZEN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSFER_FROM_UNFROZEN_TO_OPERATIONAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INITIALIZE_MASTERNODE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_MASTERNODE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INITIALIZE_NODE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_BET', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DO_BET', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=536,
  serialized_end=720,
)
_sym_db.RegisterEnumDescriptor(_NODEACCOUNTMETHOD_METHOD)


_SHAREINFO = _descriptor.Descriptor(
  name='ShareInfo',
  full_name='ShareInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_num', full_name='ShareInfo.block_num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frozen_share', full_name='ShareInfo.frozen_share', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='ShareInfo.reward', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_timestamp', full_name='ShareInfo.block_timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defrost_months', full_name='ShareInfo.defrost_months', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=139,
)


_NODEACCOUNT_REPUTATION = _descriptor.Descriptor(
  name='Reputation',
  full_name='NodeAccount.Reputation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frozen', full_name='NodeAccount.Reputation.frozen', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unfrozen', full_name='NodeAccount.Reputation.unfrozen', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=423,
)

_NODEACCOUNT = _descriptor.Descriptor(
  name='NodeAccount',
  full_name='NodeAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='NodeAccount.balance', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_state', full_name='NodeAccount.node_state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reputation', full_name='NodeAccount.reputation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixed_amount', full_name='NodeAccount.fixed_amount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='NodeAccount.min', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='NodeAccount.max', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_defrost_timestamp', full_name='NodeAccount.last_defrost_timestamp', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shares', full_name='NodeAccount.shares', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NODEACCOUNT_REPUTATION, ],
  enum_types=[
    _NODEACCOUNT_NODESTATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='bet', full_name='NodeAccount.bet',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=142,
  serialized_end=476,
)


_NODESTATE = _descriptor.Descriptor(
  name='NodeState',
  full_name='NodeState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='master_nodes', full_name='NodeState.master_nodes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=511,
)


_NODEACCOUNTMETHOD = _descriptor.Descriptor(
  name='NodeAccountMethod',
  full_name='NodeAccountMethod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODEACCOUNTMETHOD_METHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=720,
)


_NODEACCOUNTINTERNALTRANSFERPAYLOAD = _descriptor.Descriptor(
  name='NodeAccountInternalTransferPayload',
  full_name='NodeAccountInternalTransferPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='NodeAccountInternalTransferPayload.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=773,
)


_SETBETPAYLOAD = _descriptor.Descriptor(
  name='SetBetPayload',
  full_name='SetBetPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fixed_amount', full_name='SetBetPayload.fixed_amount', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='SetBetPayload.min', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='SetBetPayload.max', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='bet', full_name='SetBetPayload.bet',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=775,
  serialized_end=851,
)

_NODEACCOUNT_REPUTATION.containing_type = _NODEACCOUNT
_NODEACCOUNT.fields_by_name['node_state'].enum_type = _NODEACCOUNT_NODESTATE
_NODEACCOUNT.fields_by_name['reputation'].message_type = _NODEACCOUNT_REPUTATION
_NODEACCOUNT.fields_by_name['shares'].message_type = _SHAREINFO
_NODEACCOUNT_NODESTATE.containing_type = _NODEACCOUNT
_NODEACCOUNT.oneofs_by_name['bet'].fields.append(
  _NODEACCOUNT.fields_by_name['fixed_amount'])
_NODEACCOUNT.fields_by_name['fixed_amount'].containing_oneof = _NODEACCOUNT.oneofs_by_name['bet']
_NODEACCOUNT.oneofs_by_name['bet'].fields.append(
  _NODEACCOUNT.fields_by_name['min'])
_NODEACCOUNT.fields_by_name['min'].containing_oneof = _NODEACCOUNT.oneofs_by_name['bet']
_NODEACCOUNT.oneofs_by_name['bet'].fields.append(
  _NODEACCOUNT.fields_by_name['max'])
_NODEACCOUNT.fields_by_name['max'].containing_oneof = _NODEACCOUNT.oneofs_by_name['bet']
_NODEACCOUNTMETHOD_METHOD.containing_type = _NODEACCOUNTMETHOD
_SETBETPAYLOAD.oneofs_by_name['bet'].fields.append(
  _SETBETPAYLOAD.fields_by_name['fixed_amount'])
_SETBETPAYLOAD.fields_by_name['fixed_amount'].containing_oneof = _SETBETPAYLOAD.oneofs_by_name['bet']
_SETBETPAYLOAD.oneofs_by_name['bet'].fields.append(
  _SETBETPAYLOAD.fields_by_name['min'])
_SETBETPAYLOAD.fields_by_name['min'].containing_oneof = _SETBETPAYLOAD.oneofs_by_name['bet']
_SETBETPAYLOAD.oneofs_by_name['bet'].fields.append(
  _SETBETPAYLOAD.fields_by_name['max'])
_SETBETPAYLOAD.fields_by_name['max'].containing_oneof = _SETBETPAYLOAD.oneofs_by_name['bet']
DESCRIPTOR.message_types_by_name['ShareInfo'] = _SHAREINFO
DESCRIPTOR.message_types_by_name['NodeAccount'] = _NODEACCOUNT
DESCRIPTOR.message_types_by_name['NodeState'] = _NODESTATE
DESCRIPTOR.message_types_by_name['NodeAccountMethod'] = _NODEACCOUNTMETHOD
DESCRIPTOR.message_types_by_name['NodeAccountInternalTransferPayload'] = _NODEACCOUNTINTERNALTRANSFERPAYLOAD
DESCRIPTOR.message_types_by_name['SetBetPayload'] = _SETBETPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareInfo = _reflection.GeneratedProtocolMessageType('ShareInfo', (_message.Message,), dict(
  DESCRIPTOR = _SHAREINFO,
  __module__ = 'node_account_pb2'
  # @@protoc_insertion_point(class_scope:ShareInfo)
  ))
_sym_db.RegisterMessage(ShareInfo)

NodeAccount = _reflection.GeneratedProtocolMessageType('NodeAccount', (_message.Message,), dict(

  Reputation = _reflection.GeneratedProtocolMessageType('Reputation', (_message.Message,), dict(
    DESCRIPTOR = _NODEACCOUNT_REPUTATION,
    __module__ = 'node_account_pb2'
    # @@protoc_insertion_point(class_scope:NodeAccount.Reputation)
    ))
  ,
  DESCRIPTOR = _NODEACCOUNT,
  __module__ = 'node_account_pb2'
  # @@protoc_insertion_point(class_scope:NodeAccount)
  ))
_sym_db.RegisterMessage(NodeAccount)
_sym_db.RegisterMessage(NodeAccount.Reputation)

NodeState = _reflection.GeneratedProtocolMessageType('NodeState', (_message.Message,), dict(
  DESCRIPTOR = _NODESTATE,
  __module__ = 'node_account_pb2'
  # @@protoc_insertion_point(class_scope:NodeState)
  ))
_sym_db.RegisterMessage(NodeState)

NodeAccountMethod = _reflection.GeneratedProtocolMessageType('NodeAccountMethod', (_message.Message,), dict(
  DESCRIPTOR = _NODEACCOUNTMETHOD,
  __module__ = 'node_account_pb2'
  # @@protoc_insertion_point(class_scope:NodeAccountMethod)
  ))
_sym_db.RegisterMessage(NodeAccountMethod)

NodeAccountInternalTransferPayload = _reflection.GeneratedProtocolMessageType('NodeAccountInternalTransferPayload', (_message.Message,), dict(
  DESCRIPTOR = _NODEACCOUNTINTERNALTRANSFERPAYLOAD,
  __module__ = 'node_account_pb2'
  # @@protoc_insertion_point(class_scope:NodeAccountInternalTransferPayload)
  ))
_sym_db.RegisterMessage(NodeAccountInternalTransferPayload)

SetBetPayload = _reflection.GeneratedProtocolMessageType('SetBetPayload', (_message.Message,), dict(
  DESCRIPTOR = _SETBETPAYLOAD,
  __module__ = 'node_account_pb2'
  # @@protoc_insertion_point(class_scope:SetBetPayload)
  ))
_sym_db.RegisterMessage(SetBetPayload)


# @@protoc_insertion_point(module_scope)
