# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obligatory_payment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='obligatory_payment.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18obligatory_payment.proto\"\x1a\n\x18ObligatoryPaymentPayload\"?\n\x17ObligatoryPaymentMethod\"$\n\x06Method\x12\x1a\n\x16PAY_OBLIGATORY_PAYMENT\x10\x00\x62\x06proto3')
)



_OBLIGATORYPAYMENTMETHOD_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='ObligatoryPaymentMethod.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAY_OBLIGATORY_PAYMENT', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=83,
  serialized_end=119,
)
_sym_db.RegisterEnumDescriptor(_OBLIGATORYPAYMENTMETHOD_METHOD)


_OBLIGATORYPAYMENTPAYLOAD = _descriptor.Descriptor(
  name='ObligatoryPaymentPayload',
  full_name='ObligatoryPaymentPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=54,
)


_OBLIGATORYPAYMENTMETHOD = _descriptor.Descriptor(
  name='ObligatoryPaymentMethod',
  full_name='ObligatoryPaymentMethod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBLIGATORYPAYMENTMETHOD_METHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=119,
)

_OBLIGATORYPAYMENTMETHOD_METHOD.containing_type = _OBLIGATORYPAYMENTMETHOD
DESCRIPTOR.message_types_by_name['ObligatoryPaymentPayload'] = _OBLIGATORYPAYMENTPAYLOAD
DESCRIPTOR.message_types_by_name['ObligatoryPaymentMethod'] = _OBLIGATORYPAYMENTMETHOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObligatoryPaymentPayload = _reflection.GeneratedProtocolMessageType('ObligatoryPaymentPayload', (_message.Message,), dict(
  DESCRIPTOR = _OBLIGATORYPAYMENTPAYLOAD,
  __module__ = 'obligatory_payment_pb2'
  # @@protoc_insertion_point(class_scope:ObligatoryPaymentPayload)
  ))
_sym_db.RegisterMessage(ObligatoryPaymentPayload)

ObligatoryPaymentMethod = _reflection.GeneratedProtocolMessageType('ObligatoryPaymentMethod', (_message.Message,), dict(
  DESCRIPTOR = _OBLIGATORYPAYMENTMETHOD,
  __module__ = 'obligatory_payment_pb2'
  # @@protoc_insertion_point(class_scope:ObligatoryPaymentMethod)
  ))
_sym_db.RegisterMessage(ObligatoryPaymentMethod)


# @@protoc_insertion_point(module_scope)
